### PR TITLE
add check executable

### PR DESCRIPTION
**Pull request by davidbirdsong**
check executable, throws exceptions if file missing or missing exec bit

### CODE REVIEW

**Comment by davidbirdsong** [comment]
not sure about these travis errors. can't tell if they're related to this PR

**Comment by cablehead** [comment]
Just looking at this: with this sort of thing, it's generally better to ask forgiveness than permission. ie. just try and execute and then signal an error if it fails. For example, there's a tiny race here where permissions could be changed on the file in between checking if it's OK to run, and trying to run it.

Levee actually needs work in this area too. It'd be good to fix up the feedback you get from the child process for how the execution attempt went...

**Comment by cablehead** [comment]
There's an issue with the udp tests with PyPy.. PyPy is too quick! and the tests don't account for that udp can drop frames. I also need to pull OSX from the travis matrix. Python's not supported on their OSX setup, I think.

**Comment by cablehead** [comment]
Thinking through possible APIs... perhaps child.done could throw an exception if the status code isn't 0? That might be a bit extreme though? This isn't documented yet, as I'm not 100% sure I'm parsing it right, but the exitcode is available on the child, after done signals:

https://github.com/cablehead/vanilla/blob/master/vanilla/process.py#L59

Would that be sufficient?

**Comment by davidbirdsong** [comment]
I see the issue w/ race conditions, but the issue w/ exit codes is that
there isn't an exit code for a process that fails to exec(at least that I
know of.)

I was trying to emulate the exceptions that subprocess.Popen throws when
you pass in a non-executable or a missing file.

**Comment by cablehead** [comment]
What do you think of this behavior?

https://github.com/cablehead/vanilla/blob/master/tests/unit/test_process.py#L27

**Comment by cablehead** [comment]
based on: http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by davidbirdsong** [comment]
yeah, that looks good. didn't know about those particular exit codes.

**Comment by cablehead** [comment]
I'm pushed at patch to intercept python's OSError exception and synthesize
them:

https://github.com/cablehead/vanilla/blob/master/vanilla/process.py#L166

**Comment by cablehead** [comment]
pushed to pypi as tag v0.1.15

**Pull request closed without merging**
